# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

#Pack1 -------------------
  #MonteOlimpo.Base.Core.Data
  #MonteOlimpo.Base.Core.Domain
  #MonteOlimpo.Base.Core.Specification
  #MonteOlimpo.Base.Core.CrossCutting

  Pack1Version: '1.0.3'
  Pack1PushToNuget: false

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-monte-olimpo-base'
    organization: 'mmarlonms'
    scannerMode: 'MSBuild'
    projectKey: 'monte-olimpo-base'
    projectName: 'monte-olimpo-base'


- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'


   # Prepare publish files
- task: DotNetCoreCLI@2
  displayName: Prepare Publish Files
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/**/MonteOlimpo.Base.Core.*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: False

# Publish the artifacts
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts


###########################  Start Package 1 ###########################

# Publish MonteOlimpo.Base.Core.Specification to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack MonteOlimpo.Base.Core.Specification
  condition: eq(variables['Pack1PushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/MonteOlimpo.Base.Core.Specification.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: Pack1Version
- task: NuGetCommand@2
  displayName: Push MonteOlimpo.Base.Core.Specification to NuGet.org
  condition: eq(variables['Pack1PushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/MonteOlimpo.Base.Core.Specification.*.nupkg'
    publishFeedCredentials: NuggetConnect

    # Publish MonteOlimpo.Base.Core.Domain to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack MonteOlimpo.Base.Core.Domain
  condition: eq(variables['Pack1PushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/MonteOlimpo.Base.Core.Domain.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: Pack1Version
- task: NuGetCommand@2
  displayName: Push MonteOlimpo.Base.Core.Domain to NuGet.org
  condition: eq(variables['Pack1PushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/MonteOlimpo.Base.Core.Domain.*.nupkg'
    publishFeedCredentials: NuggetConnect


    # Publish MonteOlimpo.Base.Core.Data to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack MonteOlimpo.Base.Core.Data
  condition: eq(variables['Pack1PushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/MonteOlimpo.Base.Core.Data.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: Pack1Version
- task: NuGetCommand@2
  displayName: Push MonteOlimpo.Base.Core.Data to NuGet.org
  condition: eq(variables['Pack1PushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/MonteOlimpo.Base.Core.Data.*.nupkg'
    publishFeedCredentials: NuggetConnect

    
###########################  End Package 1 ###########################


